name: C++ CI with Makefile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgtest-dev cmake

      - name: Cache Google Test
        uses: actions/cache@v3
        with:
          path: /usr/src/googletest
          key: ${{ runner.os }}-googletest

      - name: Build main executable
        run: make main

      - name: Build and run tests
        run: |
          make tests
          ./tests --gtest_output=xml:test_results.xml

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test_results.xml

      - name: Clean all
        run: make cleanall
